'use client';

import { Share2 } from 'lucide-react';
import { cn } from '@/lib/utils';
import { Idea } from '@/lib/types';
import { ActionButton } from './ActionButton';

interface ShareButtonProps {
  idea: Idea;
  onShare?: (idea: Idea) => void;
  className?: string;
}

export function ShareButton({ idea, onShare, className }: ShareButtonProps) {
  const handleShare = async () => {
    const shareData = {
      title: 'Check out this startup idea!',
      text: `${idea.oneLiner || idea.rawIdeaText}\n\nGenerated by IdeaSpark`,
      url: window.location.href,
    };

    try {
      if (navigator.share && navigator.canShare?.(shareData)) {
        await navigator.share(shareData);
      } else {
        // Fallback to clipboard
        await navigator.clipboard.writeText(
          `${shareData.title}\n\n${shareData.text}\n\n${shareData.url}`
        );
        // You could show a toast notification here
        console.log('Copied to clipboard!');
      }
      
      onShare?.(idea);
    } catch (error) {
      console.error('Error sharing:', error);
    }
  };

  return (
    <ActionButton
      variant="icon"
      onClick={handleShare}
      className={cn('text-text-secondary hover:text-text-primary', className)}
    >
      <Share2 className="w-5 h-5" />
    </ActionButton>
  );
}
